from typing import Any


DDL = """
CREATE TABLE IF NOT EXISTS public.classifica (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_giocatore bigint NOT NULL REFERENCES public.giocatori(id),
    partite_giocate numeric,
    primo numeric,
    secondo numeric,
    terzo numeric
);
"""


MAIN_RANKING_QUERY = """
SELECT
    g.nome,
    c.partite_giocate,
    c.primo,
    c.secondo,
    c.terzo
FROM classifica AS c
JOIN giocatori AS g ON g.id = c.id_giocatore
ORDER BY g.nome
"""


def fetch_main_ranking(connection) -> dict[str, dict[str, Any]]:
    rows = connection.execute(MAIN_RANKING_QUERY).fetchall()
    return {
        row["nome"].strip().upper(): {
            "partite": row["partite_giocate"],
            "primo": row["primo"],
            "secondo": row["secondo"],
            "terzo": row["terzo"],
        }
        for row in rows
    }
