from typing import Any


DDL = """
CREATE TABLE IF NOT EXISTS public.giocatori (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    nome text,
    note text,
    soprannome text,
    user_id uuid,
    role text
);
"""


PLAYER_COLUMNS = (
    "id",
    "nome",
    "soprannome",
    "note",
    "user_id",
    "role",
)


def fetch_players(connection) -> list[dict[str, Any]]:
    rows = connection.execute(
        """
        SELECT id, nome, soprannome, note, user_id, role
        FROM giocatori
        ORDER BY nome
        """
    ).fetchall()
    return [dict(row) for row in rows]
