from typing import Any

from database.query_logging import execute_logged


DDL = """
CREATE TABLE IF NOT EXISTS public.giocatori (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    nome text,
    note text,
    soprannome text,
    user_id uuid,
    role text
);
"""


PLAYER_COLUMNS = (
    "id",
    "nome",
    "soprannome",
    "note",
    "user_id",
    "role",
)


def fetch_players(connection) -> list[dict[str, Any]]:
    rows = execute_logged(
        connection,
        """
        SELECT id, nome, soprannome, note, user_id, role
        FROM giocatori
        ORDER BY nome
        """
    ).fetchall()
    return [dict(row) for row in rows]


def fetch_user_profile(connection, email: str) -> dict[str, Any] | None:
    row = execute_logged(
        connection,
        """
        SELECT g.nome, g.soprannome, u.email
        FROM public.giocatori AS g
        JOIN auth.users AS u ON u.id = g.user_id
        WHERE lower(u.email) = lower(%s)
        """,
        (email,),
    ).fetchone()
    return dict(row) if row else None
