from typing import Any


DDL = """
CREATE TABLE IF NOT EXISTS public.mesi (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_giocatore bigint NOT NULL REFERENCES public.giocatori(id),
    gennaio numeric,
    febbraio numeric,
    marzo numeric,
    aprile numeric,
    maggio numeric,
    giugno numeric,
    luglio numeric,
    agosto numeric,
    settembre numeric,
    ottobre numeric,
    novembre numeric,
    dicembre numeric
);
"""


MONTH_COLUMNS = (
    "gennaio", "febbraio", "marzo", "aprile", "maggio", "giugno",
    "luglio", "agosto", "settembre", "ottobre", "novembre", "dicembre",
)

MONTHLY_RANKING_QUERY = """
SELECT
    g.nome,
    m.gennaio,
    m.febbraio,
    m.marzo,
    m.aprile,
    m.maggio,
    m.giugno,
    m.luglio,
    m.agosto,
    m.settembre,
    m.ottobre,
    m.novembre,
    m.dicembre
FROM mesi AS m
JOIN giocatori AS g ON g.id = m.id_giocatore
ORDER BY g.nome
"""


def fetch_monthly_ranking(connection) -> dict[str, list[Any]]:
    rows = connection.execute(MONTHLY_RANKING_QUERY).fetchall()
    return {
        row["nome"].strip().upper(): [
            row[column] if row[column] is not None else 0
            for column in MONTH_COLUMNS
        ]
        for row in rows
    }
